# Generated by Django 5.1.5 on 2025-02-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfjob',
            name='pdf_files',
            field=models.JSONField(blank=True, default=list, help_text='List of PDF file paths or URLs', null=True),
        ),
        migrations.AlterField(
            model_name='pdfjob',
            name='pulse_studio_response',
            field=models.JSONField(blank=True, default=dict, help_text='Response data from Pulse Studio API', null=True),
        ),
    ]
