# Generated by Django 5.1.5 on 2025-02-01 08:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pdfjob_pdf_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfjob',
            name='pdf_files',
        ),
        migrations.CreateModel(
            name='PdfFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='pdfs/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_files', to='core.pdfjob')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
